use std::fmt;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
pub struct Position {
    pub offset: usize,
    pub line: usize,
    pub column: usize,
}

impl Position {
    pub const fn new(offset: usize, line: usize, column: usize) -> Self {
        Self {
            offset,
            line,
            column,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
pub struct Span {
    pub start: Position,
    pub end: Position,
}

impl Span {
    pub const fn new(start: Position, end: Position) -> Self {
        Self { start, end }
    }

    pub const fn between(start: Span, end: Span) -> Self {
        Self {
            start: start.start,
            end: end.end,
        }
    }

    pub const fn point(position: Position) -> Self {
        Self {
            start: position,
            end: position,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TokenKind {
    Number(String),
    String(String),
    Template { value: String, invalid_escape: bool },
    Identifier(String),
    PrivateName(String),
    RegExp { body: String, flags: String },
    Eof,
    Null,
    False,
    True,
    If,
    Else,
    Return,
    Var,
    This,
    Delete,
    Void,
    Typeof,
    New,
    In,
    Instanceof,
    Do,
    While,
    For,
    Break,
    Continue,
    Switch,
    Case,
    Default,
    Throw,
    Try,
    Catch,
    Finally,
    Function,
    Debugger,
    With,
    Class,
    Const,
    Enum,
    Export,
    Extends,
    Import,
    Super,
    Implements,
    Interface,
    Let,
    Package,
    Private,
    Protected,
    Public,
    Static,
    Yield,
    Await,
    LeftParen,
    RightParen,
    LeftBrace,
    RightBrace,
    LeftBracket,
    RightBracket,
    Dot,
    Semicolon,
    Comma,
    Colon,
    Question,
    At,
    OptionalChain,
    Ellipsis,
    Arrow,
    Increment,
    Decrement,
    Add,
    Sub,
    Mul,
    Div,
    Mod,
    Pow,
    Assign,
    AddAssign,
    SubAssign,
    MulAssign,
    DivAssign,
    ModAssign,
    PowAssign,
    Shl,
    Sar,
    Shr,
    ShlAssign,
    SarAssign,
    ShrAssign,
    BitAnd,
    BitOr,
    BitXor,
    BitNot,
    AndAssign,
    OrAssign,
    XorAssign,
    LogicalAnd,
    LogicalOr,
    NullishCoalescing,
    LogicalAndAssign,
    LogicalOrAssign,
    NullishAssign,
    Not,
    Eq,
    StrictEq,
    Ne,
    StrictNe,
    Lt,
    Lte,
    Gt,
    Gte,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TokenTag {
    Number,
    String,
    Template,
    Identifier,
    PrivateName,
    RegExp,
    Eof,
    Null,
    False,
    True,
    If,
    Else,
    Return,
    Var,
    This,
    Delete,
    Void,
    Typeof,
    New,
    In,
    Instanceof,
    Do,
    While,
    For,
    Break,
    Continue,
    Switch,
    Case,
    Default,
    Throw,
    Try,
    Catch,
    Finally,
    Function,
    Debugger,
    With,
    Class,
    Const,
    Enum,
    Export,
    Extends,
    Import,
    Super,
    Implements,
    Interface,
    Let,
    Package,
    Private,
    Protected,
    Public,
    Static,
    Yield,
    Await,
    LeftParen,
    RightParen,
    LeftBrace,
    RightBrace,
    LeftBracket,
    RightBracket,
    Dot,
    Semicolon,
    Comma,
    Colon,
    Question,
    At,
    OptionalChain,
    Ellipsis,
    Arrow,
    Increment,
    Decrement,
    Add,
    Sub,
    Mul,
    Div,
    Mod,
    Pow,
    Assign,
    AddAssign,
    SubAssign,
    MulAssign,
    DivAssign,
    ModAssign,
    PowAssign,
    Shl,
    Sar,
    Shr,
    ShlAssign,
    SarAssign,
    ShrAssign,
    BitAnd,
    BitOr,
    BitXor,
    BitNot,
    AndAssign,
    OrAssign,
    XorAssign,
    LogicalAnd,
    LogicalOr,
    NullishCoalescing,
    LogicalAndAssign,
    LogicalOrAssign,
    NullishAssign,
    Not,
    Eq,
    StrictEq,
    Ne,
    StrictNe,
    Lt,
    Lte,
    Gt,
    Gte,
}

impl TokenKind {
    pub const fn tag(&self) -> TokenTag {
        match self {
            Self::Number(_) => TokenTag::Number,
            Self::String(_) => TokenTag::String,
            Self::Template { .. } => TokenTag::Template,
            Self::Identifier(_) => TokenTag::Identifier,
            Self::PrivateName(_) => TokenTag::PrivateName,
            Self::RegExp { .. } => TokenTag::RegExp,
            Self::Eof => TokenTag::Eof,
            Self::Null => TokenTag::Null,
            Self::False => TokenTag::False,
            Self::True => TokenTag::True,
            Self::If => TokenTag::If,
            Self::Else => TokenTag::Else,
            Self::Return => TokenTag::Return,
            Self::Var => TokenTag::Var,
            Self::This => TokenTag::This,
            Self::Delete => TokenTag::Delete,
            Self::Void => TokenTag::Void,
            Self::Typeof => TokenTag::Typeof,
            Self::New => TokenTag::New,
            Self::In => TokenTag::In,
            Self::Instanceof => TokenTag::Instanceof,
            Self::Do => TokenTag::Do,
            Self::While => TokenTag::While,
            Self::For => TokenTag::For,
            Self::Break => TokenTag::Break,
            Self::Continue => TokenTag::Continue,
            Self::Switch => TokenTag::Switch,
            Self::Case => TokenTag::Case,
            Self::Default => TokenTag::Default,
            Self::Throw => TokenTag::Throw,
            Self::Try => TokenTag::Try,
            Self::Catch => TokenTag::Catch,
            Self::Finally => TokenTag::Finally,
            Self::Function => TokenTag::Function,
            Self::Debugger => TokenTag::Debugger,
            Self::With => TokenTag::With,
            Self::Class => TokenTag::Class,
            Self::Const => TokenTag::Const,
            Self::Enum => TokenTag::Enum,
            Self::Export => TokenTag::Export,
            Self::Extends => TokenTag::Extends,
            Self::Import => TokenTag::Import,
            Self::Super => TokenTag::Super,
            Self::Implements => TokenTag::Implements,
            Self::Interface => TokenTag::Interface,
            Self::Let => TokenTag::Let,
            Self::Package => TokenTag::Package,
            Self::Private => TokenTag::Private,
            Self::Protected => TokenTag::Protected,
            Self::Public => TokenTag::Public,
            Self::Static => TokenTag::Static,
            Self::Yield => TokenTag::Yield,
            Self::Await => TokenTag::Await,
            Self::LeftParen => TokenTag::LeftParen,
            Self::RightParen => TokenTag::RightParen,
            Self::LeftBrace => TokenTag::LeftBrace,
            Self::RightBrace => TokenTag::RightBrace,
            Self::LeftBracket => TokenTag::LeftBracket,
            Self::RightBracket => TokenTag::RightBracket,
            Self::Dot => TokenTag::Dot,
            Self::Semicolon => TokenTag::Semicolon,
            Self::Comma => TokenTag::Comma,
            Self::Colon => TokenTag::Colon,
            Self::Question => TokenTag::Question,
            Self::At => TokenTag::At,
            Self::OptionalChain => TokenTag::OptionalChain,
            Self::Ellipsis => TokenTag::Ellipsis,
            Self::Arrow => TokenTag::Arrow,
            Self::Increment => TokenTag::Increment,
            Self::Decrement => TokenTag::Decrement,
            Self::Add => TokenTag::Add,
            Self::Sub => TokenTag::Sub,
            Self::Mul => TokenTag::Mul,
            Self::Div => TokenTag::Div,
            Self::Mod => TokenTag::Mod,
            Self::Pow => TokenTag::Pow,
            Self::Assign => TokenTag::Assign,
            Self::AddAssign => TokenTag::AddAssign,
            Self::SubAssign => TokenTag::SubAssign,
            Self::MulAssign => TokenTag::MulAssign,
            Self::DivAssign => TokenTag::DivAssign,
            Self::ModAssign => TokenTag::ModAssign,
            Self::PowAssign => TokenTag::PowAssign,
            Self::Shl => TokenTag::Shl,
            Self::Sar => TokenTag::Sar,
            Self::Shr => TokenTag::Shr,
            Self::ShlAssign => TokenTag::ShlAssign,
            Self::SarAssign => TokenTag::SarAssign,
            Self::ShrAssign => TokenTag::ShrAssign,
            Self::BitAnd => TokenTag::BitAnd,
            Self::BitOr => TokenTag::BitOr,
            Self::BitXor => TokenTag::BitXor,
            Self::BitNot => TokenTag::BitNot,
            Self::AndAssign => TokenTag::AndAssign,
            Self::OrAssign => TokenTag::OrAssign,
            Self::XorAssign => TokenTag::XorAssign,
            Self::LogicalAnd => TokenTag::LogicalAnd,
            Self::LogicalOr => TokenTag::LogicalOr,
            Self::NullishCoalescing => TokenTag::NullishCoalescing,
            Self::LogicalAndAssign => TokenTag::LogicalAndAssign,
            Self::LogicalOrAssign => TokenTag::LogicalOrAssign,
            Self::NullishAssign => TokenTag::NullishAssign,
            Self::Not => TokenTag::Not,
            Self::Eq => TokenTag::Eq,
            Self::StrictEq => TokenTag::StrictEq,
            Self::Ne => TokenTag::Ne,
            Self::StrictNe => TokenTag::StrictNe,
            Self::Lt => TokenTag::Lt,
            Self::Lte => TokenTag::Lte,
            Self::Gt => TokenTag::Gt,
            Self::Gte => TokenTag::Gte,
        }
    }

    pub fn identifier(&self) -> Option<&str> {
        match self {
            Self::Identifier(name) | Self::PrivateName(name) => Some(name),
            _ => None,
        }
    }

    pub fn string_value(&self) -> Option<&str> {
        match self {
            Self::String(value) => Some(value),
            Self::Template { value, .. } => Some(value),
            _ => None,
        }
    }

    pub fn number_text(&self) -> Option<&str> {
        match self {
            Self::Number(value) => Some(value),
            _ => None,
        }
    }

    pub const fn keyword_text(&self) -> Option<&'static str> {
        match self {
            Self::Null => Some("null"),
            Self::False => Some("false"),
            Self::True => Some("true"),
            Self::If => Some("if"),
            Self::Else => Some("else"),
            Self::Return => Some("return"),
            Self::Var => Some("var"),
            Self::This => Some("this"),
            Self::Delete => Some("delete"),
            Self::Void => Some("void"),
            Self::Typeof => Some("typeof"),
            Self::New => Some("new"),
            Self::In => Some("in"),
            Self::Instanceof => Some("instanceof"),
            Self::Do => Some("do"),
            Self::While => Some("while"),
            Self::For => Some("for"),
            Self::Break => Some("break"),
            Self::Continue => Some("continue"),
            Self::Switch => Some("switch"),
            Self::Case => Some("case"),
            Self::Default => Some("default"),
            Self::Throw => Some("throw"),
            Self::Try => Some("try"),
            Self::Catch => Some("catch"),
            Self::Finally => Some("finally"),
            Self::Function => Some("function"),
            Self::Debugger => Some("debugger"),
            Self::With => Some("with"),
            Self::Class => Some("class"),
            Self::Const => Some("const"),
            Self::Enum => Some("enum"),
            Self::Export => Some("export"),
            Self::Extends => Some("extends"),
            Self::Import => Some("import"),
            Self::Super => Some("super"),
            Self::Implements => Some("implements"),
            Self::Interface => Some("interface"),
            Self::Let => Some("let"),
            Self::Package => Some("package"),
            Self::Private => Some("private"),
            Self::Protected => Some("protected"),
            Self::Public => Some("public"),
            Self::Static => Some("static"),
            Self::Yield => Some("yield"),
            Self::Await => Some("await"),
            _ => None,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Token {
    pub tag: TokenTag,
    pub kind: TokenKind,
    pub span: Span,
    pub leading_line_break: bool,
    pub escaped: bool,
}

impl Token {
    pub const fn tag(&self) -> TokenTag {
        self.tag
    }
}

impl fmt::Display for TokenTag {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{self:?}")
    }
}

impl fmt::Display for TokenKind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Number(value) => write!(f, "{value}"),
            Self::String(value) => write!(f, "\"{value}\""),
            Self::Template { value, .. } => write!(f, "`{value}`"),
            Self::Identifier(name) => write!(f, "{name}"),
            Self::PrivateName(name) => write!(f, "#{name}"),
            Self::RegExp { body, flags } => write!(f, "/{body}/{flags}"),
            kind => {
                if let Some(keyword) = kind.keyword_text() {
                    write!(f, "{keyword}")
                } else {
                    write!(f, "{:?}", kind.tag())
                }
            }
        }
    }
}
