pub mod optimization {
    use value::JSValue;

    #[allow(dead_code)]
    pub fn optimize_bytecode(code: Vec<u32>, constants: Vec<JSValue>) -> (Vec<u32>, Vec<JSValue>) {
        (code, constants)
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Opcode {
    Mov,
    LoadK,
    Add,
    GetPropIc,
    Call,
    Jmp,
    LoadI,
    JmpTrue,
    JmpFalse,
    SetPropIc,
    AddAccImm8,
    IncAcc,
    LoadThis,
    Load0,
    Load1,
    Eq,
    Lt,
    Lte,
    AddAcc,
    SubAcc,
    MulAcc,
    DivAcc,
    LoadNull,
    LoadTrue,
    LoadFalse,
    LoadGlobalIc,
    SetGlobalIc,
    Typeof,
    ToNum,
    ToStr,
    IsUndef,
    IsNull,
    SubAccImm8,
    MulAccImm8,
    DivAccImm8,
    AddStrAcc,
    AddI,
    SubI,
    MulI,
    DivI,
    ModI,
    Mod,
    Neg,
    Inc,
    Dec,
    AddStr,
    ToPrimitive,
    GetPropAcc,
    SetPropAcc,
    GetIdxFast,
    SetIdxFast,
    LoadArg,
    LoadAcc,
    StrictEq,
    StrictNeq,
    BitAnd,
    BitOr,
    BitXor,
    BitNot,
    Shl,
    Shr,
    Ushr,
    Pow,
    LogicalAnd,
    LogicalOr,
    NullishCoalesce,
    In,
    Instanceof,
    GetLengthIc,
    ArrayPushAcc,
    NewObj,
    NewArr,
    NewFunc,
    NewClass,
    GetProp,
    SetProp,
    GetIdxIc,
    SetIdxIc,
    GetGlobal,
    SetGlobal,
    GetUpval,
    SetUpval,
    GetScope,
    SetScope,
    ResolveScope,
    GetSuper,
    SetSuper,
    DeleteProp,
    HasProp,
    Keys,
    ForIn,
    IteratorNext,
    Spread,
    Destructure,
    CreateEnv,
    LoadName,
    StoreName,
    InitName,
    LoadClosure,
    NewThis,
    TypeofName,
    JmpEq,
    JmpNeq,
    JmpLt,
    JmpLte,
    LoopIncJmp,
    Switch,
    LoopHint,
    Ret,
    RetU,
    TailCall,
    Construct,
    CallVar,
    Enter,
    Leave,
    Yield,
    Await,
    Throw,
    Try,
    EndTry,
    Catch,
    Finally,
    CallIc,
    CallIcVar,
    ProfileType,
    ProfileCall,
    ProfileRet,
    CheckType,
    CheckStruct,
    CheckIc,
    IcInit,
    IcUpdate,
    IcMiss,
    OsrEntry,
    ProfileHotLoop,
    OsrExit,
    JitHint,
    SafetyCheck,
    GetPropIcCall,
    IncJmpFalseLoop,
    LoadKAddAcc,
    AddMov,
    EqJmpTrue,
    GetPropAccCall,
    LoadKMulAcc,
    LtJmp,
    GetPropIcMov,
    GetPropAddImmSetPropIc,
    AddAccImm8Mov,
    CallIcSuper,
    LoadThisCall,
    EqJmpFalse,
    LoadKSubAcc,
    GetLengthIcCall,
    AddStrAccMov,
    IncAccJmp,
    GetPropChainAcc,
    TestJmpTrue,
    LoadArgCall,
    MulAccMov,
    LteJmpLoop,
    NewObjInitProp,
    ProfileHotCall,
    Call2SubIAdd,
    Call1SubI,
    JmpLteFalse,
    RetReg,
    AddI32,
    AddF64,
    SubI32,
    SubF64,
    MulI32,
    MulF64,
    // Superinstructions
    RetIfLteI,
    AddAccReg,
    Call1Add,
    Call2Add,
    LoadKAdd,
    LoadKCmp,
    CmpJmp,
    GetPropCall,
    CallRet,
    // Specialized opcodes
    AddI32Fast,
    AddF64Fast,
    SubI32Fast,
    MulI32Fast,
    EqI32Fast,
    LtI32Fast,
    JmpI32Fast,
    GetPropMono,
    CallMono,
    // Call opcodes
    Call0,
    Call1,
    Call2,
    Call3,
    CallMethod1,
    CallMethod2,
    // New arithmetic superinstructions
    LoadAdd,
    LoadSub,
    LoadMul,
    LoadInc,
    LoadDec,
    // New comparison superinstructions
    LoadCmpEq,
    LoadCmpLt,
    LoadJfalse,
    LoadCmpEqJfalse,
    LoadCmpLtJfalse,
    // Property access superinstructions
    LoadGetProp,
    LoadGetPropCmpEq,
    // Pareto 80% property access superinstructions with IC
    GetProp2Ic,
    GetProp3Ic,
    GetElem,
    SetElem,
    GetPropElem,
    CallMethodIc,
    CallMethod2Ic,
    LtF64,
    LteF64,
    JmpLtF64,
    JmpLteF64,
    JmpLteFalseF64,
    // Assertion opcodes
    AssertValue,
    AssertOk,
    AssertFail,
    AssertThrows,
    AssertDoesNotThrow,
    AssertRejects,
    AssertDoesNotReject,
    AssertEqual,
    AssertNotEqual,
    AssertDeepEqual,
    AssertNotDeepEqual,
    AssertStrictEqual,
    AssertNotStrictEqual,
    AssertDeepStrictEqual,
    AssertNotDeepStrictEqual,
    Reserved(u8),
}

impl From<u8> for Opcode {
    fn from(value: u8) -> Self {
        match value {
            0 => Self::Mov,
            1 => Self::LoadK,
            2 => Self::Add,
            3 => Self::GetPropIc,
            4 => Self::Call,
            5 => Self::Jmp,
            6 => Self::LoadI,
            7 => Self::JmpTrue,
            8 => Self::JmpFalse,
            9 => Self::SetPropIc,
            10 => Self::AddAccImm8,
            11 => Self::IncAcc,
            12 => Self::LoadThis,
            13 => Self::Load0,
            14 => Self::Load1,
            15 => Self::Eq,
            16 => Self::Lt,
            17 => Self::Lte,
            18 => Self::AddAcc,
            19 => Self::SubAcc,
            20 => Self::MulAcc,
            21 => Self::DivAcc,
            22 => Self::LoadNull,
            23 => Self::LoadTrue,
            24 => Self::LoadFalse,
            25 => Self::LoadGlobalIc,
            26 => Self::SetGlobalIc,
            27 => Self::Typeof,
            28 => Self::ToNum,
            29 => Self::ToStr,
            30 => Self::IsUndef,
            31 => Self::IsNull,
            32 => Self::SubAccImm8,
            33 => Self::MulAccImm8,
            34 => Self::DivAccImm8,
            35 => Self::AddStrAcc,
            36 => Self::AddI,
            37 => Self::SubI,
            38 => Self::MulI,
            39 => Self::DivI,
            40 => Self::ModI,
            61 => Self::Mod,
            41 => Self::Neg,
            42 => Self::Inc,
            43 => Self::Dec,
            44 => Self::AddStr,
            45 => Self::ToPrimitive,
            46 => Self::GetPropAcc,
            47 => Self::SetPropAcc,
            48 => Self::GetIdxFast,
            49 => Self::SetIdxFast,
            50 => Self::LoadArg,
            51 => Self::LoadAcc,
            52 => Self::StrictEq,
            53 => Self::StrictNeq,
            54 => Self::BitAnd,
            55 => Self::BitOr,
            56 => Self::BitXor,
            57 => Self::BitNot,
            58 => Self::Shl,
            59 => Self::Shr,
            60 => Self::Ushr,
            64 => Self::GetLengthIc,
            65 => Self::ArrayPushAcc,
            66 => Self::NewObj,
            67 => Self::NewArr,
            68 => Self::NewFunc,
            69 => Self::NewClass,
            70 => Self::GetProp,
            71 => Self::SetProp,
            72 => Self::GetIdxIc,
            73 => Self::SetIdxIc,
            74 => Self::GetGlobal,
            75 => Self::SetGlobal,
            76 => Self::GetUpval,
            77 => Self::SetUpval,
            78 => Self::GetScope,
            79 => Self::SetScope,
            80 => Self::ResolveScope,
            81 => Self::GetSuper,
            82 => Self::SetSuper,
            83 => Self::DeleteProp,
            84 => Self::HasProp,
            85 => Self::Keys,
            86 => Self::ForIn,
            87 => Self::IteratorNext,
            88 => Self::Spread,
            89 => Self::Destructure,
            90 => Self::CreateEnv,
            91 => Self::LoadName,
            92 => Self::StoreName,
            123 => Self::InitName,
            93 => Self::LoadClosure,
            94 => Self::NewThis,
            95 => Self::TypeofName,
            96 => Self::JmpEq,
            97 => Self::JmpNeq,
            98 => Self::JmpLt,
            99 => Self::JmpLte,
            100 => Self::LoopIncJmp,
            101 => Self::Switch,
            102 => Self::LoopHint,
            103 => Self::Ret,
            104 => Self::RetU,
            105 => Self::TailCall,
            106 => Self::Construct,
            107 => Self::CallVar,
            108 => Self::Enter,
            109 => Self::Leave,
            110 => Self::Yield,
            111 => Self::Await,
            112 => Self::Throw,
            113 => Self::Try,
            114 => Self::EndTry,
            115 => Self::Catch,
            116 => Self::Finally,
            117 => Self::Pow,
            118 => Self::LogicalAnd,
            119 => Self::LogicalOr,
            120 => Self::NullishCoalesce,
            121 => Self::In,
            122 => Self::Instanceof,
            128 => Self::CallIc,
            129 => Self::CallIcVar,
            160 => Self::ProfileType,
            161 => Self::ProfileCall,
            162 => Self::ProfileRet,
            163 => Self::CheckType,
            164 => Self::CheckStruct,
            165 => Self::CheckIc,
            166 => Self::IcInit,
            167 => Self::IcUpdate,
            168 => Self::IcMiss,
            169 => Self::OsrEntry,
            170 => Self::ProfileHotLoop,
            171 => Self::OsrExit,
            172 => Self::JitHint,
            173 => Self::SafetyCheck,
            200 => Self::GetPropIcCall,
            201 => Self::IncJmpFalseLoop,
            202 => Self::LoadKAddAcc,
            203 => Self::AddMov,
            204 => Self::EqJmpTrue,
            205 => Self::GetPropAccCall,
            206 => Self::LoadKMulAcc,
            207 => Self::LtJmp,
            208 => Self::GetPropIcMov,
            209 => Self::GetPropAddImmSetPropIc,
            210 => Self::AddAccImm8Mov,
            211 => Self::CallIcSuper,
            212 => Self::LoadThisCall,
            213 => Self::EqJmpFalse,
            214 => Self::LoadKSubAcc,
            215 => Self::GetLengthIcCall,
            216 => Self::AddStrAccMov,
            217 => Self::IncAccJmp,
            218 => Self::GetPropChainAcc,
            219 => Self::TestJmpTrue,
            220 => Self::LoadArgCall,
            221 => Self::MulAccMov,
            222 => Self::LteJmpLoop,
            223 => Self::NewObjInitProp,
            224 => Self::ProfileHotCall,
            239 => Self::Call2SubIAdd,
            240 => Self::Call1SubI,
            241 => Self::JmpLteFalse,
            242 => Self::RetReg,
            243 => Self::AddI32,
            244 => Self::AddF64,
            245 => Self::SubI32,
            246 => Self::SubF64,
            247 => Self::MulI32,
            248 => Self::MulF64,
            // Superinstructions
            249 => Self::RetIfLteI,
            250 => Self::AddAccReg,
            251 => Self::Call1Add,
            252 => Self::Call2Add,
            253 => Self::LoadKAdd,
            254 => Self::LoadKCmp,
            255 => Self::CmpJmp,
            // Specialized opcodes
            130 => Self::AddI32Fast,
            131 => Self::AddF64Fast,
            132 => Self::SubI32Fast,
            133 => Self::MulI32Fast,
            134 => Self::EqI32Fast,
            135 => Self::LtI32Fast,
            136 => Self::JmpI32Fast,
            137 => Self::GetPropMono,
            138 => Self::CallMono,
            // Call opcodes
            139 => Self::Call0,
            140 => Self::Call1,
            141 => Self::Call2,
            142 => Self::Call3,
            143 => Self::CallMethod1,
            144 => Self::CallMethod2,
            // Superinstruction variants
            145 => Self::GetPropCall,
            146 => Self::CallRet,
            // Assertion opcodes
            147 => Self::AssertValue,
            148 => Self::AssertOk,
            149 => Self::AssertFail,
            150 => Self::AssertThrows,
            151 => Self::AssertDoesNotThrow,
            152 => Self::AssertRejects,
            153 => Self::AssertDoesNotReject,
            154 => Self::AssertEqual,
            155 => Self::AssertNotEqual,
            156 => Self::AssertDeepEqual,
            157 => Self::AssertNotDeepEqual,
            158 => Self::AssertStrictEqual,
            159 => Self::AssertNotStrictEqual,
            174 => Self::AssertDeepStrictEqual,
            175 => Self::AssertNotDeepStrictEqual,
            // New arithmetic superinstructions
            176 => Self::LoadAdd,
            177 => Self::LoadSub,
            178 => Self::LoadMul,
            179 => Self::LoadInc,
            180 => Self::LoadDec,
            // New comparison superinstructions
            181 => Self::LoadCmpEq,
            182 => Self::LoadCmpLt,
            183 => Self::LoadJfalse,
            184 => Self::LoadCmpEqJfalse,
            185 => Self::LoadCmpLtJfalse,
            // Property access superinstructions
            186 => Self::LoadGetProp,
            187 => Self::LoadGetPropCmpEq,
            // Pareto 80% property access superinstructions with IC
            188 => Self::GetProp2Ic,
            189 => Self::GetProp3Ic,
            190 => Self::GetElem,
            191 => Self::SetElem,
            192 => Self::GetPropElem,
            193 => Self::CallMethodIc,
            194 => Self::CallMethod2Ic,
            195 => Self::LtF64,
            196 => Self::LteF64,
            197 => Self::JmpLtF64,
            198 => Self::JmpLteF64,
            199 => Self::JmpLteFalseF64,
            other => Self::Reserved(other),
        }
    }
}

impl Opcode {
    /// Convert an Opcode to its u8 representation
    #[allow(clippy::wrong_self_convention)]
    pub fn as_u8(self) -> u8 {
        match self {
            Self::Mov => 0,
            Self::LoadK => 1,
            Self::Add => 2,
            Self::GetPropIc => 3,
            Self::Call => 4,
            Self::Jmp => 5,
            Self::LoadI => 6,
            Self::JmpTrue => 7,
            Self::JmpFalse => 8,
            Self::SetPropIc => 9,
            Self::AddAccImm8 => 10,
            Self::IncAcc => 11,
            Self::LoadThis => 12,
            Self::Load0 => 13,
            Self::Load1 => 14,
            Self::Eq => 15,
            Self::Lt => 16,
            Self::Lte => 17,
            Self::AddAcc => 18,
            Self::SubAcc => 19,
            Self::MulAcc => 20,
            Self::DivAcc => 21,
            Self::LoadNull => 22,
            Self::LoadTrue => 23,
            Self::LoadFalse => 24,
            Self::LoadGlobalIc => 25,
            Self::SetGlobalIc => 26,
            Self::Typeof => 27,
            Self::ToNum => 28,
            Self::ToStr => 29,
            Self::IsUndef => 30,
            Self::IsNull => 31,
            Self::SubAccImm8 => 32,
            Self::MulAccImm8 => 33,
            Self::DivAccImm8 => 34,
            Self::AddStrAcc => 35,
            Self::AddI => 36,
            Self::SubI => 37,
            Self::MulI => 38,
            Self::DivI => 39,
            Self::ModI => 40,
            Self::Mod => 61,
            Self::Neg => 41,
            Self::Inc => 42,
            Self::Dec => 43,
            Self::AddStr => 44,
            Self::ToPrimitive => 45,
            Self::GetPropAcc => 46,
            Self::SetPropAcc => 47,
            Self::GetIdxFast => 48,
            Self::SetIdxFast => 49,
            Self::LoadArg => 50,
            Self::LoadAcc => 51,
            Self::StrictEq => 52,
            Self::StrictNeq => 53,
            Self::BitAnd => 54,
            Self::BitOr => 55,
            Self::BitXor => 56,
            Self::BitNot => 57,
            Self::Shl => 58,
            Self::Shr => 59,
            Self::Ushr => 60,
            Self::Pow => 117,
            Self::LogicalAnd => 118,
            Self::LogicalOr => 119,
            Self::NullishCoalesce => 120,
            Self::In => 121,
            Self::Instanceof => 122,
            Self::GetLengthIc => 64,
            Self::ArrayPushAcc => 65,
            Self::NewObj => 66,
            Self::NewArr => 67,
            Self::NewFunc => 68,
            Self::NewClass => 69,
            Self::GetProp => 70,
            Self::SetProp => 71,
            Self::GetIdxIc => 72,
            Self::SetIdxIc => 73,
            Self::GetGlobal => 74,
            Self::SetGlobal => 75,
            Self::GetUpval => 76,
            Self::SetUpval => 77,
            Self::GetScope => 78,
            Self::SetScope => 79,
            Self::ResolveScope => 80,
            Self::GetSuper => 81,
            Self::SetSuper => 82,
            Self::DeleteProp => 83,
            Self::HasProp => 84,
            Self::Keys => 85,
            Self::ForIn => 86,
            Self::IteratorNext => 87,
            Self::Spread => 88,
            Self::Destructure => 89,
            Self::CreateEnv => 90,
            Self::LoadName => 91,
            Self::StoreName => 92,
            Self::InitName => 123,
            Self::LoadClosure => 93,
            Self::NewThis => 94,
            Self::TypeofName => 95,
            Self::JmpEq => 96,
            Self::JmpNeq => 97,
            Self::JmpLt => 98,
            Self::JmpLte => 99,
            Self::LoopIncJmp => 100,
            Self::Switch => 101,
            Self::LoopHint => 102,
            Self::Ret => 103,
            Self::RetU => 104,
            Self::TailCall => 105,
            Self::Construct => 106,
            Self::CallVar => 107,
            Self::Enter => 108,
            Self::Leave => 109,
            Self::Yield => 110,
            Self::Await => 111,
            Self::Throw => 112,
            Self::Try => 113,
            Self::EndTry => 114,
            Self::Catch => 115,
            Self::Finally => 116,
            Self::CallIc => 128,
            Self::CallIcVar => 129,
            Self::ProfileType => 160,
            Self::ProfileCall => 161,
            Self::ProfileRet => 162,
            Self::CheckType => 163,
            Self::CheckStruct => 164,
            Self::CheckIc => 165,
            Self::IcInit => 166,
            Self::IcUpdate => 167,
            Self::IcMiss => 168,
            Self::OsrEntry => 169,
            Self::ProfileHotLoop => 170,
            Self::OsrExit => 171,
            Self::JitHint => 172,
            Self::SafetyCheck => 173,
            Self::GetPropIcCall => 200,
            Self::IncJmpFalseLoop => 201,
            Self::LoadKAddAcc => 202,
            Self::AddMov => 203,
            Self::EqJmpTrue => 204,
            Self::GetPropAccCall => 205,
            Self::LoadKMulAcc => 206,
            Self::LtJmp => 207,
            Self::GetPropIcMov => 208,
            Self::GetPropAddImmSetPropIc => 209,
            Self::AddAccImm8Mov => 210,
            Self::CallIcSuper => 211,
            Self::LoadThisCall => 212,
            Self::EqJmpFalse => 213,
            Self::LoadKSubAcc => 214,
            Self::GetLengthIcCall => 215,
            Self::AddStrAccMov => 216,
            Self::IncAccJmp => 217,
            Self::GetPropChainAcc => 218,
            Self::TestJmpTrue => 219,
            Self::LoadArgCall => 220,
            Self::MulAccMov => 221,
            Self::LteJmpLoop => 222,
            Self::NewObjInitProp => 223,
            Self::ProfileHotCall => 224,
            Self::Call2SubIAdd => 239,
            Self::Call1SubI => 240,
            Self::JmpLteFalse => 241,
            Self::RetReg => 242,
            Self::AddI32 => 243,
            Self::AddF64 => 244,
            Self::SubI32 => 245,
            Self::SubF64 => 246,
            Self::MulI32 => 247,
            Self::MulF64 => 248,
            // Superinstructions
            Self::RetIfLteI => 249,
            Self::AddAccReg => 250,
            Self::Call1Add => 251,
            Self::Call2Add => 252,
            Self::LoadKAdd => 253,
            Self::LoadKCmp => 254,
            Self::CmpJmp => 255,
            // Specialized opcodes
            Self::AddI32Fast => 130,
            Self::AddF64Fast => 131,
            Self::SubI32Fast => 132,
            Self::MulI32Fast => 133,
            Self::EqI32Fast => 134,
            Self::LtI32Fast => 135,
            Self::JmpI32Fast => 136,
            Self::GetPropMono => 137,
            Self::CallMono => 138,
            // Call opcodes
            Self::Call0 => 139,
            Self::Call1 => 140,
            Self::Call2 => 141,
            Self::Call3 => 142,
            Self::CallMethod1 => 143,
            Self::CallMethod2 => 144,
            // New arithmetic superinstructions
            Self::LoadAdd => 176,
            Self::LoadSub => 177,
            Self::LoadMul => 178,
            Self::LoadInc => 179,
            Self::LoadDec => 180,
            // New comparison superinstructions
            Self::LoadCmpEq => 181,
            Self::LoadCmpLt => 182,
            Self::LoadJfalse => 183,
            Self::LoadCmpEqJfalse => 184,
            Self::LoadCmpLtJfalse => 185,
            // Property access superinstructions
            Self::LoadGetProp => 186,
            Self::LoadGetPropCmpEq => 187,
            // Pareto 80% property access superinstructions with IC
            Self::GetProp2Ic => 188,
            Self::GetProp3Ic => 189,
            Self::GetElem => 190,
            Self::SetElem => 191,
            Self::GetPropElem => 192,
            Self::CallMethodIc => 193,
            Self::CallMethod2Ic => 194,
            Self::LtF64 => 195,
            Self::LteF64 => 196,
            Self::JmpLtF64 => 197,
            Self::JmpLteF64 => 198,
            Self::JmpLteFalseF64 => 199,
            // Superinstruction variants
            Self::GetPropCall => 145,
            Self::CallRet => 146,
            // Assertion opcodes
            Self::AssertValue => 147,
            Self::AssertOk => 148,
            Self::AssertFail => 149,
            Self::AssertThrows => 150,
            Self::AssertDoesNotThrow => 151,
            Self::AssertRejects => 152,
            Self::AssertDoesNotReject => 153,
            Self::AssertEqual => 154,
            Self::AssertNotEqual => 155,
            Self::AssertDeepEqual => 156,
            Self::AssertNotDeepEqual => 157,
            Self::AssertStrictEqual => 158,
            Self::AssertNotStrictEqual => 159,
            Self::AssertDeepStrictEqual => 174,
            Self::AssertNotDeepStrictEqual => 175,
            Self::Reserved(value) => value,
        }
    }
}
